language: perl
perl:
- '5.18'
- '5.16'
- '5.14'

env:
  global:
    - secure: "C+aEGxxDdNbEpoQ/XspXP/T8fvG0eE0iZE7QTklHvR4nHbuO1y9Is/LYwR+d0dgniMd9NiQtvQb5iGQCWL3NWn9r+sK2EO9zmniUZDGjOSPuVDYSmWc5fhZ/ira1mKnXECxC7fG45cLyV8zfmg3Zo8yOmGuA6oM36akEufz/0aY="
    - secure: "V98gDu77N3bD+q/2T+xgeHwnL74IrGL8xMsoUoqa1Thkd+GMM7ql9gfRmvUy2bKzgbeDP9hWitfOkj2ZjNsTPYLAUPj2CDyak7tyYgSK9yC6y7OiOGyxgjgGUofF+Mp0xr1w0iHCw13QvQcNqRuxFGpMgf72dL0sRiopLzEaE2c="
    - secure: "ZlDFC7HCT5jzDfMVt4ErlB98182RYUq3FZqEGu4X2GrOdttDTfIkUg8PLcgpQKkBbS82W/kPaX6lk6lPQ9gjckA+UPGcecrFpgcJu2gv145DehBz80VlQZiY8O/ammLse5u4fHDE9/zHqPwR0+z7ZtiZuKf9bGR1ysR66Tn0HG0="

